POST http://localhost:8080/tarefas
Content-Type: application/json

{
  "titulo": "Estudar Git",
  "descricao": "Praticar commits e pushs no DevTask",
  "status": "PENDENTE"
}

###

GET http://localhost:8080/tarefas/999